title: Community Digital Garden Docs
description: A community-built collection of helpful guides, bugs, fixes, and customizations.
theme: just-the-docs
color_scheme: nil
favicon_ico: "/assets/favicon.svg"


url: https://wiseguru.github.io/Community-Digital-Garden-Docs

aux_links:
  Community Digital Garden Docs Repository: https://github.com/WiseGuru/Community-Digital-Garden-Docs

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/mmcesim/mmcesim.org" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Callouts
callouts:
## Red
  warning:
    title: Warning
    color: red
## Yellow
  alert:
    title: Alert
    color: yellow
## Green
  success:
    title: Success
    color: green
## Blue
  tip:
    title: Tip
    color: blue
## Purple
  example:
    title: Example
    color: purple

