title: Community Digital Garden Docs
description: A community-built collection of helpful guides, bugs, fixes, and customizations.
theme: just-the-docs
color_scheme: nil
favicon_ico: "/assets/favicon.svg"


url: https://wiseguru.github.io/Community-Digital-Garden-Docs

aux_links:
  Community Digital Garden Docs Repository: https://github.com/WiseGuru/Community-Digital-Garden-Docs

# Callouts
callouts:
## Red
  warning:
    title: Warning
    color: red
## Yellow
  alert:
    title: Alert
    color: yellow
## Green
  success:
    title: Success
    color: green
## Blue
  reminder:
    title: Reminder
    color: blue
  tip:
    title: Tip
    color: blue
## Purple
  example:
    title: Example
    color: purple

