title: Unofficial Digital Garden Docs
description: A user-edited collection of helpful guides, bugs, fixes, and customizations.
theme: just-the-docs
favicon_ico: "/assets/favicon.svg"


url: https://wiseguru.github.io/Unofficial-Digital-Garden-Docs

aux_links:
  Template Repository: https://github.com/WiseGuru/Unofficial-Digital-Garden-Docs



# Callouts
callouts:
  warning:
    title: Warning
    color: red
  reminder:
    title: Reminder
    color: blue
  success:
    title: Success
    color: green
  tip:
    title: Note
    color: teal
